final List<Map<String, dynamic>> sections = [
  {
    'name': 'Coffee',
    'images': [
      'cappucino',
      'espresso',
      'black coffee',
      'americano',
      'cold coffee',
    ],
    'item': [
      'Cappuccino',
      'Espresso',
      'Black Coffee',
      'Americano',
      'Cold Coffee',
    ],
    'useDuplicate': [true, true, false, true, true],
    'price': [60, 50, 30, 45, 55], // Common price
    'priceRegular': [
      50,
      40,
      null,
      35,
      45,
    ], // Regular price (only for `useDuplicate: true`)
    'priceLarge': [
      70,
      60,
      null,
      55,
      65,
    ], // Large price (only for `useDuplicate: true`)
  },
  {
    'name': 'Frappe',
    'images': ['caramel frappe', 'Strawberry-Frappe', 'mocha-frappe'],
    'item': ['Caramel Frappe', 'Strawberry Frappe', 'Mocha Frappe'],
    'useDuplicate': [true, true, true],
    'price': [70, 100, 60],
    'priceRegular': [60, 90, 50],
    'priceLarge': [80, 120, 70],
  },
  {
    'name': 'Tea',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Cold Coffee',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Krusher',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Maggie',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Fries',
    'images': [
      'peri fries',
      'Loaded-Bacon-Cheese-Fries-3',
      'salted French-fries',
      'cheesy fries',
      'mint fries',
    ],
    'item': [
      'Peri Fries',
      'Loaded Fries',
      'Salted French Fries',
      'Cheesy Fries',
      'Mint Fries',
    ],
    'useDuplicate': [false, false, false, false, false],
    'price': [70, 100, 60, 80, 65],
  },
  {
    'name': 'Burger',
    'images': ['Secret-Veg-Cheeseburgers-c981dd6', 'schezwan burger'],
    'item': ['Veg Cheeseburger', 'Schezwan Burger'],
    'useDuplicate': [false, false],
    'price': [65, 70],
  },
  {
    'name': 'Sandwich',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Wraps',
    'images': ['veg wrap', 'paneer wrap', 'schezwan wrap'],
    'item': ['Veg Wrap', 'Paneer Wrap', 'Schezwan Wrap'],
    'useDuplicate': [false, false, false],
    'price': [70, 100, 60],
  },
  {
    'name': 'Soup',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Rice Bowl',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Mojito',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Hot Chocolate',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Sweet Corn',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Dessert',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
  {
    'name': 'Pasta',
    'images': [],
    'item': [],
    'useDuplicate': [],
    'price': [],
    'priceRegular': [],
    'priceLarge': [],
  },
];
